[book]
title="Phaktionz TCG"
author="Mustafif Khan"

[output.html]
git-repository-url = "https://github.com/rust-lang/cargo/tree/master/src/doc/src"

[output.html.search]
limit-results = 20
teaser-word-count = 30
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2
copy-js = true